### ISSUE TITLE
[Improvement] Lazy imports in MagicObj.py

### ISSUE THREAD

**Issue by antopolskiy** [innocuous-ai/innocuousbook#1]
Right now `MagicObj` imports all library integrations on its import. 

Given that for some projects some of the integrations will not be used (like, on AWS, Azure integrations are never used, and vice versa; pytorch projects will not use tensorflow, etc), making imports lazy (i.e. by localizing them into the functions that use them) would help to avoid issues with compatibility when not necessary (example: right now I have an issue locally with `ray.tune.integration.keras` which I actually never need) and overhead.

**Comment by NoamRosenberg** [comment]
Hi @antopolskiy, I pushed a lazy importing fix. Kindly test out the newer version of innocuous-magic on pip.

**Comment by antopolskiy** [comment]
It works now. Thank you!
